### ISSUE TITLE
V1.7.0 Broken when using Python2 on startup

### ISSUE THREAD

**Issue by orgalinq** [EricHigdon/OctoPrint-RGB_status#70] opened 2020-06-13 13:20 UTC
Upgraded today from 1.6 to 1.7. After that the plugin in not working anymore. The toggle switch in the nav-bar visually switches on and off on the screen but not the lights.

Using PI 3b+

**Comment by EricHigdon** [comment] 2020-06-13 13:21
Can you share your OctoPrint.log please?

You can find it in the logging section of the settings.

**Comment by orgalinq** [comment] 2020-06-13 13:46
Here it is:


  OrgaLinQ


kokkelmanlanden 23
7542 JC  Enschede
+31(0)651 608 840

(IPhone bericht)

**Comment by EricHigdon** [comment] 2020-06-13 13:51
@orgalinq the file is not attached. 

I don’t think GitHub supports adding files from email attachments if that’s what you are trying to do.

**Comment by orgalinq** [comment] 2020-06-13 14:07
Ok, here is the octoprint.log

Thank you.
[octoprint.log](https://github.com/EricHigdon/OctoPrint-RGB_status/files/4774741/octoprint.log)

**Comment by NameOfTheDragon** [comment] 2020-06-13 17:01
I can confirm this. On mine, the effect freezes but the lights don't turn off. 

Also, I noticed that saving the settings sometimes freezes the effect until the lights are toggled off and on from the navbar. However in the process of making this comment I noticed that I had my type of LED set incorrectly, and after I changed it I could no longer reproduce the freeze-after-settings-change thing. The lights still don't turn off though.

I'm using a strip of 7 neopixels, part ADA1460, LED type SK6812IC. Here's my config screen in case it helps...
![image](https://user-images.githubusercontent.com/1268490/84574680-efa20700-ad9f-11ea-80f7-4d93afcbfc24.png)

**Comment by EricHigdon** [comment] 2020-06-13 17:34
@NameOfTheDragon Can you share your OctoPrint.log as well please?

**Comment by NameOfTheDragon** [comment] 2020-06-13 17:45
[octoprint.log](https://github.com/EricHigdon/OctoPrint-RGB_status/files/4775098/octoprint.log)
Here's my log.

I've noticed an additional related issue. If the lights are toggled off then on during a print, they resume in the incorrect status (I get idle state, rainbow wipe, instead of printing state, all white).

**Comment by cp2004** [comment] 2020-06-13 20:41
@NameOfTheDragon Does it resume the printing state once the progress bar changes again? That's how it's working my end. 
@EricHigdon Maybe want to save a 'last effect' state so that on lights on you can just go straight back into it?

**Comment by cp2004** [comment] 2020-06-13 20:42
For the main issue, for me it works, but is not an instant response. (Couple seconds delay) Could be due to the time it takes for effects to exit, I will have a look at if there are any waits that could be sped up

**Comment by EricHigdon** [comment] 2020-06-14 00:59
@orgalinq @NameOfTheDragon This issue should be fixed in V1.7.1.
Please update and let me know if you still have this problem.

**Closed as completed by EricHigdon** 2020-06-14 00:59 UTC
Labels: bug

**Comment by NameOfTheDragon** [comment] 2020-06-14 04:02
I'm not sure if this is an odd Octoprint thing, but when installing the 1.7.1 update, after restarting Octoprint is prompting me to install it again. The plugin manager says I've still got 1.7.0 installed. When I try to reinstall it, in the installer output it says something like "This version was already installed, forcing a re-install". The fix IS working though, I can now toggle the lights on and off.

**Comment by EricHigdon** [comment] 2020-06-14 05:00
@NameOfTheDragon Try re-installing one last time please. I just forgot to change the version number in the plugin code.

**Comment by orgalinq** [comment] 2020-06-14 16:01
Have upgraded from 1.7.0 to 1.7.1. All right now, the LEDs can now switch on and off. At first glance everything else works ok too.
Happy with it, thank you!
