### ISSUE TITLE
Turn of LED if not print

### ISSUE THREAD

**Issue by kirax999** [EricHigdon/OctoPrint-RGB_status#25] opened 2019-07-24 13:21 UTC
Hi,

I am looking for how I can do to cut the led once the print finished and if no printing is in progress, I try to put the idl in color 0 0 0 but it remains in white light if I do not print.

What to do ?

Thank you for your work this is really good except segfault from time to time octoprint server x)

PS: I'm using Octoprint distribution

**Comment by EricHigdon** [comment] 2019-08-06 18:30
This is a duplicate of #15.

**Closed as completed** 2019-08-06 18:30 UTC
